# Generated by Django 4.0.3 on 2022-03-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='', max_length=100)),
                ('firstNAme', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='firstNAme',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='userName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
