# Generated by Django 4.0.3 on 2022-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_professor_student_course_student_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectId', models.CharField(default='', max_length=100)),
                ('firstNAme', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
