# Generated by Django 4.0.3 on 2022-04-01 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ProjectId',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='firstNAme',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lastName',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='open', max_length=100),
        ),
    ]
