# Generated by Django 4.0.3 on 2022-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_btpproject_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='btpproject',
            name='total_applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='btpproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100),
        ),
    ]
