# Generated by Django 4.0.3 on 2022-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_btpproject_total_applications_alter_btpproject_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpproject',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='open', max_length=100),
        ),
    ]
