# Generated by Django 4.0.3 on 2022-04-02 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_collegepeople_alter_btpproject_publish_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.RemoveField(
            model_name='collegepeople',
            name='firstNAme',
        ),
        migrations.RemoveField(
            model_name='collegepeople',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='collegepeople',
            name='userName',
        ),
        migrations.AddField(
            model_name='collegepeople',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100),
        ),
    ]
