# Generated by Django 4.0.3 on 2022-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_professor_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegepeople',
            name='cpi',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
