# Generated by Django 4.0.3 on 2022-04-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_collegepeople_cpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='open', max_length=100),
        ),
    ]
