# Generated by Django 4.0.3 on 2022-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_btpproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegepeople',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
