# Generated by Django 4.0.3 on 2022-04-13 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_remove_collegepeople_slug_name_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='open', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], default='rejected', max_length=100)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ManyToManyField(to='accounts.btpproject')),
            ],
        ),
    ]
