# Generated by Django 4.0.3 on 2022-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_btpproject_status_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='btpproject',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='accept_status',
            field=models.CharField(choices=[('requested', 'requested'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='rejected', max_length=100),
        ),
    ]
