# Generated by Django 4.0.3 on 2022-04-18 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_points_btpproject_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('agenda', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.btpproject')),
            ],
        ),
    ]
