# Generated by Django 4.0.3 on 2022-04-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_mom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='accept_status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('requested', 'requested'), ('accepted', 'accepted')], default='rejected', max_length=100),
        ),
    ]
