# Generated by Django 4.0.3 on 2022-04-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_mom_minutes_alter_btpproject_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mom',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='accept_status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'accepted'), ('requested', 'requested')], default='rejected', max_length=100),
        ),
    ]
