# Generated by Django 4.0.3 on 2022-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_content_mom_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='accept_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('requested', 'requested'), ('rejected', 'rejected')], default='rejected', max_length=100),
        ),
    ]
