# Generated by Django 4.0.3 on 2022-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_mom_points_alter_btpproject_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='accept_status',
            field=models.CharField(choices=[('requested', 'requested'), ('rejected', 'rejected'), ('accepted', 'accepted')], default='rejected', max_length=100),
        ),
    ]
