# Generated by Django 4.0.3 on 2022-04-19 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_projectmember_accept_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='accept_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('requested', 'requested'), ('rejected', 'rejected')], default='rejected', max_length=100),
        ),
        migrations.CreateModel(
            name='TeamNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('agenda', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.btpproject')),
            ],
        ),
    ]
