# Generated by Django 4.0.3 on 2022-04-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_btpproject_students_required_alter_btpproject_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btpproject',
            name='projectid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='btpproject',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='accept_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('requested', 'requested')], default='rejected', max_length=100),
        ),
    ]
